### ISSUE TITLE
type ="tel" would be correct

### ISSUE THREAD

**Issue by OzodaKhamdamova** [kozimov786/pixer#1]
https://github.com/kozimov786/pixer/blob/14c9c74579daae3f7bbaba280b7b70a0670dce8b/index.html#L161

you should have used type"tel" inspite of "number"

**Comment by kozimov786** [comment]
> https://github.com/kozimov786/pixer/blob/14c9c74579daae3f7bbaba280b7b70a0670dce8b/index.html#L161
> 
> you should have used type"tel" inspite of "number"

thank you it's incorrect i fixed
